### ISSUE TITLE
Conformité INSPIRE

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/Excel-template-for-Metawal#17]
Pour la conformité INSPIRE, il est nécessaire de référencer :
* le règlement 1089/2010
* pour chaque thème indiqué dans les mots-clés INSPIRE la spécification de données correspondante

Le résultat de l'évaluation de conformité pour chacun de ces éléments doit obligatoirement être indiqué (conforme ou non conforme) - la valeur "non évalué" n'est pas acceptée.

**Comment by fdonnay** [comment]
Modification faite dans le modèle FME pour que la valeur "non-conforme" soit indiquée lorsqu'aucune vérification sur la conformité n'a été réalisée.
